[tool.commitizen]
name = "cz_conventional_commits"
version = "0.6.3"
tag_format = "v$version"
version_files = [
    "GNUmakefile:VERSION",
    "package.json:version",
    "README.md:version"
]
bump_message = "release $current_version → $new_version [skip ci]"
