# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
golang-docker-workspace: &golang-docker-workspace
  docker:
    - image: circleci/golang:1.14
  working_directory: /go/src/github.com/samanthaq/terraform-provider-circleci

python-docker-workspace: &python-docker-workspace
  docker:
    - image: circleci/python:3.8
  working_directory: /tmp/workspace

version: 2
jobs:
  build:
    <<: *golang-docker-workspace
    steps:
      - checkout
      - run:
          name: Build provider
          command: make build

  test:
    <<: *golang-docker-workspace
    steps:
      - checkout
      - run:
          name: Acceptance tests
          command: make testacc
      - run:
          name: Test sweepers
          command: make sweep

  tag-test:
    <<: *python-docker-workspace
    steps:
      - checkout:
          path: /tmp/workspace
      - run:
          name: Install commitizen
          command: |
            pip3 install --user --upgrade --upgrade-strategy eager commitizen==2.1.0
      - run:
          name: Test that creating new Git tag works
          command: |
            git config --global user.email "svc_ci_iaa@mckinsey.com"
            git config --global user.name "svc-ci-iaa"
            cz bump --yes

workflows:
  version: 2
  build-test:
    jobs:
      - build:
          context: CI_SETTINGS
      - test:
          context: CI_SETTINGS
          requires:
            - build
      - tag-test:
          context: CI_SETTINGS
